#All answers template
template = {
    'rus'     : {
        'uzcard to qiwi'        : '🔄 Отдать с Uzcard и получать на Qiwi',
        'qiwi to uzcard'        : '🔄 Отдать с Qiwi и получать на Uzcard',
        'requisites'            : '💳 Адреса моих кошельков',
        'rate'                  : '📊 Курс',
        'main_menu'             : '🏠 Главное меню',
        'plus_uzcard'           : '➕ Добавить UzCard',
        'plus_qiwi'             : '➕ Добавить Qiwi',
        'del_data'              : '🗑 Удалить данные',
        'after_del'             : "🗑 Данные удалены",
        'msg_into_requisites'   : "🗂Ваши Кошельки",
        'empty'                 : 'Пусто',
        'after_plus_uzcard'     : "Введите номер вашей карты UZCARD\n\nНапример:\n8600851264754532",
        'after_plus_qiwi'       : "Введите номер вашего QIWI кошелька\n\nНапример:\n998946166312",
        'error_num'             : "❌ Вы ввели неправильный номер, пожалуйста введите снова:",
        'error_uzcard_count_num': "❌ Номер карты должен имеет 16 цифр, пожалуйста введите снова:",
        'succes_uzcard'         : "✅ Номер вашей карты успешно сохранен",
        'succes_qiwi'           : "✅ Номер вашего кошелька успешно сохранен",
        'edit_uzcard'           : "♻️ Изменить UzCard",
        'edit_qiwi'             : "♻️ Изменить Qiwi",
        'doesnt_exist_all'      : "🚫 У вас не указаны кошельки",
        'doesnt_exist_uzcard'   : "🚫 У вас не указан номер карты UzCard",
        'doesnt_exist_qiwi'     : "🚫 У вас не указан номер Qiwi кошелька",
        'add_more'              : "⏬ Добавить ещё",
        'add_all'               : "⏬ Добавить UzCard и Qiwi",
        'add_uzcard'            : "⏬ Добавить Uzcard",
        'add_qiwi'              : "⏬ Добавить Qiwi",
    },
    'uz'     : {
        'uzcard to qiwi'        : '🔄 Qiwi Rubl sotib olish (UZS -> RUB)',
        'qiwi to uzcard'        : '🔄 Qiwi Rubl sotish (RUB -> UZS)',
        'requisites'            : '💳 Hamyonlarim',
        'rate'                  : '📊 Kurs',
        'main_menu'             : '🏠 Bosh menyu',
        'plus_uzcard'           : "➕ UzCard raqamini kiritish",
        'plus_qiwi'             : "➕ Qiwi raqamini kiritish",
        'del_data'              : "🗑 Malumotlarni o'chirish",
        'after_del'             : "🗑 Malumotlar o'chirildi",
        'msg_into_requisites'   : "🗂Sizning hamyonlaringiz",
        'empty'                 : "Kiritilmagan",
        'after_plus_uzcard'     : "UZCARD kartangiz raqamini kiriting\n\nMisol uchun:\n8600851264754532",
        'after_plus_qiwi'       : "QIWI hamyoningiz raqamini kiriting\n\nMisol uchun:\n998946166312",
        'error_num'             : "❌ Siz noto'g'ri raqam terdingiz, iltimos qayta urinib ko'ring:",
        'error_uzcard_count_num': "❌ Karta raqami 16 raqamdan iborat bo'lishi kerak, iltimos qayta urinib ko'ring:",
        'succes_uzcard'         : "✅ UzCard karta raqamingiz kiritildi",
        'succes_qiwi'           : "✅ Qiwi hamyoningiz kiritildi",
        'edit_uzcard'           : "♻️ UzCard karta raqamini o'zgartirish",
        'edit_qiwi'             : "♻️ Qiwi raqamini o'zgartirish",
        'doesnt_exist_all'      : "🚫 Sizda karta raqamlari kiritilmagan",
        'doesnt_exist_uzcard'   : "🚫 Sizda UzCard karta raqami kiritilmagan",
        'doesnt_exist_qiwi'     : "🚫 Sizda Qiwi hamyon raqami kiritilmagan",
        'add_more'              : "⏬ Yana qo'shish",
        'add_all'               : "⏬ Hamyon raqamlarini kiritish",
        'add_uzcard'            : "⏬ UzCard karta raqamini kiritish",
        'add_qiwi'              : "⏬ Qiwi karta raqamini kiritish",

    }
}